### PR TITLE
vsdownload: Add an option to skip packages that do not match host arch

### PR DESCRIPTION
**Pull request by huangqinjin**
Depends on #140.

#### Some packages have their host arch in their ids, e.g.
```
"Microsoft.VisualCpp.Tools.HostARM64.TargetX64"
"Microsoft.VisualCpp.Tools.HostARM64.TargetX86"
"Microsoft.VisualCpp.Tools.HostX64.TargetX64"
"Microsoft.VisualCpp.Tools.HostX64.TargetX86"
```

I think it is pretty safe to skip packages if their ids do not match host arch.

[PR #140](https://github.com/mstorsjo/msvc-wine/actions/runs/11194999176/job/31122154650?pr=140#step:4:49)
```
Selected 544 packages, for a total download size of 2.9 GB, install size of 8.9 GB
```

[PR #148](https://github.com/mstorsjo/msvc-wine/actions/runs/11195105784/job/31122372211?pr=148#step:4:49)
```
Selected 475 packages, for a total download size of 2.7 GB, install size of 8.5 GB
```

### CODE REVIEW

**Comment by mstorsjo** [comment]
Thanks, this looks like a nice addition! However for some cases I guess it would be nice to be able to unpack all of them; would it be possible to add an option that lets the user get all of them?

**Comment by huangqinjin** [comment]
A option is reasonable to me. But the main reason for me is that such filters based on host arch will going to be wrong in future, e.g. I want to filter packages based on their `chip`, `machineArch` and `productArch`.

Is `--only-host` a good name? What is the default value we want?

**Comment by mstorsjo** [comment]
> A option is reasonable to me. But the main reason for me is that such filters based on host arch will going to be wrong in future, e.g. I want to filter packages based on their `chip`, `machineArch` and `productArch`.
> 
> Is `--only-host` a good name? What is the default value we want?

This looks like a reasonable name, and yes, we want the default to be to only unpack things for the host arch - as normal users won't need to think about this option. Thanks!

**Review by mstorsjo — APPROVED** [review]
LGTM

**Pull request merged**
