### PR TITLE
test: Add testing of the arch specific assembler tools

### PR DESCRIPTION
**Pull request by mstorsjo**
Just testing that running the assembler exits successfully.

Adding the testing in test-cl.sh, instead of a separate test script, although I'm open to creating a separate test script if that's preferred.

CC @huangqinjin

### CODE REVIEW

**Comment by huangqinjin** [comment]
LGTM though I would prefer a separate script for `masm`.

**Comment by mstorsjo** [comment]
> LGTM though I would prefer a separate script for `masm`.

Do you mean specifically the x86 `masm` tests, or splitting all of the newly added ones here into a separate `test-asm.sh`?

**Comment by huangqinjin** [comment]
> splitting all of the newly added ones here into a separate test-asm.sh

That is what I mean. Sorry for confusion.

**Comment by mstorsjo** [comment]
Updated the branch to move the tests to a separate file. I also reordered the tests in `test.sh` to test the individual tools first before testing cmake/meson.

**Comment by huangqinjin** [comment]
LGTM!

**Pull request merged**
