### PR TITLE
github: Install Wine Mono 5.1 for Ubuntu Wine 6.0

### PR DESCRIPTION
**Pull request by huangqinjin**

### CODE REVIEW

**Comment by huangqinjin** [comment]
Wine in wine64-development package is version 6.0 https://github.com/mstorsjo/msvc-wine/actions/runs/7948162508/job/21697868326?pr=116#step:2:161

Wine in wine64 (stable) package is version 6.0.3 https://github.com/mstorsjo/msvc-wine/actions/runs/7948186049/job/21697923479?pr=116#step:2:166

I suspect there is a bug in 6.0 and got fixed in 6.0.3. 

CC @ravenexp

**Comment by ravenexp** [comment]
I don't mind reverting CI to WINE 6.0.3 if all the tests still pass, but I previously had an issue even with WINE 8.0 and PREfast static analyzer (`cl /analyze`). None of the current tests use this though.

I think it's OK to merge this now, and depending on how https://github.com/mstorsjo/msvc-wine/pull/111 fares we might need to bump WINE version again.

**Comment by mstorsjo** [comment]
> Wine in wine64-development package is version 6.0 https://github.com/mstorsjo/msvc-wine/actions/runs/7948162508/job/21697868326?pr=116#step:2:161
> 
> Wine in wine64 (stable) package is version 6.0.3 https://github.com/mstorsjo/msvc-wine/actions/runs/7948186049/job/21697923479?pr=116#step:2:166
> 
> I suspect there is a bug in 6.0 and got fixed in 6.0.3.

Right, that's plausible. Back a bunch of years ago when I set this up, `wine64-development` usually gave half a year newer version of wine (and `wine64-stable` was stuck at the `x.0.0` version, which had some bugs at the time), but if it's not needed, sticking to `-stable` certainly is reasonable.

> I don't mind reverting CI to WINE 6.0.3 if all the tests still pass, but I previously had an issue even with WINE 8.0 and PREfast static analyzer (`cl /analyze`). None of the current tests use this though.
> 
> I think it's OK to merge this now, and depending on how #111 fares we might need to bump WINE version again.

FWIW, Ubuntu 24.04 should be out not too long in the future. Currently that version seems to be providing 8.0.2; it'd be nice if they'd manage to bump it to 9.0 before that release, but I guess that's unlikely at this point? So once that's available on github actions (not sure how long it takes after the release), we can move there (as long as it's available by specifically requesting such a runner, even if the `ubuntu-latest` label hasn't been updated there).

@huangqinjin Can you rebase this after #115 was merged, to get a nice green CI run, before merging it?

**Review by mstorsjo — APPROVED** [review]

**Comment by huangqinjin** [comment]
@mstorsjo To get a nice green CI run, I think you can simply restart the job?

**Comment by huangqinjin** [comment]
OK, seems I misunderstood how CI on PR is running. Rebased now.

**Comment by mstorsjo** [comment]
> OK, seems I misunderstood how CI on PR is running. Rebased now.

No problem - I'm not sure if it depends on the PR merging style, or just because this was a rerun of the previous pipeline (with its simulated merged form), not a new attempted merge and run on top of that.

**Pull request merged**
